spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
    producer:
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092

# Service URLs for local development
services:
  flight:
    url: http://localhost:8080
  payment:
    url: http://localhost:8082
  ticket:
    url: http://localhost:8081

# Enable OTEL for Docker deployment
otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://collector:4317
  traces:
    exporter: otlp
  logs:
    exporter: none
  metrics:
    exporter: none