spring:
  kafka:
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

# Service URLs for local development
services:
  flight:
    url: http://localhost:8080
  payment:
    url: http://localhost:8082
  ticket:
    url: http://localhost:8081

# Disable OTEL for local development
otel:
  traces:
    exporter: none
  logs:
    exporter: none
  metrics:
    exporter: none