spring:
  application:
    name: payment
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    consumer:
      auto-startup: true
      enable-auto-commit: true
      auto-commit-interval: 1000
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002
    producer:
      bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

server:
  port: 8082

# Disable all endpoints except health for local testing
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Disable OTEL for local development  
otel:
  traces:
    exporter: none
  logs:
    exporter: none
  metrics:
    exporter: none