spring:
  application:
    name: payment
  cloud:
    compatibility-verifier:
      enabled: false
  kafka:
    consumer:
      auto-startup: true
      enable-auto-commit: true
      auto-commit-interval: 1000
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092
    producer:
      bootstrap-servers: Kafka00Service:9092,Kafka01Service:9092,Kafka02Service:9092

server:
  port: 8082

# Disable all endpoints except health for local testing
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Enable OTEL for Docker deployment
otel:
  exporter:
    otlp:
      protocol: grpc
      endpoint: http://collector:4317
  traces:
    exporter: otlp
  logs:
    exporter: none
  metrics:
    exporter: none